# Generated by Django 5.0.6 on 2024-05-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(choices=[('Diseño de Interiores', 'Diseño de Interiores'), ('Diseño de Espacio Público', 'Diseño de Espacio Público'), ('Proyectos en Altura', 'Proyectos en Altura'), ('Proyectos Comerciales Mediana Escala', 'Proyectos Comerciales Mediana Escala')], max_length=100),
        ),
    ]
